# OnePlus driver Makefile

obj-$(CONFIG_OEM_DEBUG_SUPORT)	+= boot_mode.o
obj-$(CONFIG_OEM_TRACE_SUPORT)	+= oem_trace.o
obj-$(CONFIG_OEM_FORCE_DUMP)	+= oem_force_dump.o
obj-$(CONFIG_OEM_PROJECT_INFO)	+= project_info.o
obj-$(CONFIG_RF_CABLE_DETECT)	+= op_rf_cable_monitor.o

obj-y += param_read_write/
