# OnePlus driver Makefile

obj-$(CONFIG_OEM_DEBUG_SUPORT)	+= boot_mode.o
obj-$(CONFIG_OEM_TRACE_SUPORT)	+= oem_trace.o
obj-$(CONFIG_OEM_FORCE_DUMP)	+= oem_force_dump.o
obj-$(CONFIG_OP_GPL_HELPER)	+= op_gpl_helper.o
obj-$(CONFIG_OP_STRUCT_OFFSET_HELPER)	+= op_struct_offset_helper.o

obj-y += param_read_write/
obj-y += coretech/
